# Generated by Django 4.2.3 on 2023-07-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blockuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='follower_user',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='following_user',
        ),
        migrations.DeleteModel(
            name='BlockUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
